### ISSUE TITLE
Changes to 2.3 upwards

### ISSUE THREAD

**Issue by Githubber616** [Momo-Studios/Cold-Sweat-Rework-Forge#359] opened 2024-08-31 12:05 UTC
> # 2.3.3
> 
> ## Fixes:
> - Fixed the hearth still accepting water if the config settings had not been updated from a previous version

**Not a fix!** Please revert it back that the config does accept water (for Hearth/icebox), if the player/mod user chose to do so/ the config has been set-up that way. Maybe put a one-time run script in that changes the config if needed.

Like: Old-config detected. Click here to prevent updating to the new waterless system.

Ice might seem easy to farm in the scenarios you had, But, I'm stuck in a dessert and the next ice is half a world away (>3km). Which I need to make more ice. See where my problem is?

As I lack the resources to travel that far (got there in copy of the world in creative). So my problem is: I can't acquire stuff for cooling as I can't travel that far, and I can't build up to that as I lack the cooling.

**Comment by MikulDev** [comment] 2024-08-31 12:12
> Maybe put a one-time run script in that changes the config if needed.

That is exactly what it does. Cold Sweat stores the last version you launched in the config file, so if it detects you're running an outdated version, it will make the necessary changes and mark it as updated.

This was indeed a fix, because leaving water as a fuel source by default was unintended behavior. If you would like to revert this change, you can add water back to the list of fuel items and it won't be removed again.

> the next ice is half a world away (>3km). Which I need to make more ice. See where my problem is?

Not really. Most deserts get cold at night, and you can use that to freeze ice. If you build it at high elevation, you can pretty easily make an ice farm. I've done this exact thing myself before.

**Comment by Githubber616** [comment] 2024-09-01 01:15
The biome is flourishing dunes.

Temperatures at day are 50°C and 29°C at night. In spring.

I made a copy of said world and am in creative. Despite spamming iceboxes (I filled them … and added smoke stacks) I couldn't get the temperature below 5°C.

With spamming soul campfires, I can only get the temperature below 0°C and below the surface level. But no Ice is building. No torches or anything nearby.
I even had trouble getting ice to grow in the frozen oceans.

Edit: Clarification: There are islands in the frozen oceans, some of which can get quite big. If I remove all snow from them, and ice blocks, they are around +15°C. So too warm to freeze water in the new system.

But even if I get the temperature below 1°C, (And the easiest is to use blue ice. Otherwise, you need ungodly amounts of iceboxes and soul camp fires, and you then only get it down to ~0°C) anywhere where doesn't snow fall, water doesn't freeze.

My last test involved a liberal use of blue ice and soul camp fire, which brought the temperature down to -32°C at night in an ice adjacent biome (stopped day night cycle) Even then it doesn't freeze. Rain or not. Open sky or not.

**Comment by MikulDev** [comment] 2024-09-02 15:24
Because block temperature is very expensive to calculate, Cold Sweat has to use it very sparingly. This means block temperature doesn't actually affect water freezing into ice (with the exception of soul fire, which freezes adjacent water blocks even in any temperature. I will extend this functionality to soul campfires as well).

Other environmental factors, like time of day and altitude, can possibly help you reach 0°C. The biome you're in has very hot night temperatures, so it might be difficult, but might still be possible. It would be easier if you found a neighboring biome and set up the farm there.

**Comment by Githubber616** [comment] 2024-09-02 17:59
I wasn't able to get it to freeze in any biome. Only in frozen oceans when it snowed it froze. didn't try soul fire, though, only soul campfire.
I was about to disable all temperature effects in config and play without.

**Comment by MikulDev** [comment] 2024-09-02 20:00
You can if you'd like. Like I originally said, you can also add back water as a fuel source and it won't be removed again. I was just explaining how the mechanics worked as there seemed to have been some confusion. I have personally gotten good results in most biomes at night if the altitude is high enough. 

At any rate, I'll be closing this issue as the original report has been addressed.

**Closed as completed by MikulDev** 2024-09-02 20:00 UTC
Labels: intentional
