### ISSUE TITLE
1.19.2 Render Screen Client Crash on Tooltips

### ISSUE THREAD

**Issue by parmleyhunt** [Momo-Studios/Cold-Sweat-Rework-Forge#299] opened 2024-05-21 04:41 UTC
When looking at tooltips in JEI client will crash with out of  bounds exception. There is no pattern and/or specific items that causes this and it is not every time either. However, when I have noticed what item was looking at before it crashed, the item had nothing todo with Cold Sweat. I hoped that updating would fix it as your changelog had something similar. However until fixed I will have to remove. Thanks anyway for adding that extra annoying layer to Survival :D

[post_crash_report.txt](https://github.com/Momo-Softworks/Cold-Sweat/files/15384567/post_crash_report.txt)

**Comment by MikulDev** [comment] 2024-05-24 04:50
Duplicate of #290, #286, #283, and #279. This will be fixed in the next beta version

**Closed as completed** 2024-05-24 04:55 UTC
