### ISSUE TITLE
[1.18.2] [2.1.10-b03] Waterskins in Hotbar Slots Causes Crash

### ISSUE THREAD

**Issue by D-Bigboy-302** [Momo-Studios/Cold-Sweat-Rework-Forge#54] opened 2022-05-11 10:05 UTC
Forge: 40.1.19
Mod Version: 2.1.10-b03

Upon taking waterskin out of icebox and putting it in your invenotry, the game crashes.
[crash-2022-05-11_05.37.11-client.txt](https://github.com/Momo-Studios/Cold-Sweat/files/8668878/crash-2022-05-11_05.37.11-client.txt)

It also crashes whenever you try to load up the same world that crashed.
[crash-2022-05-11_05.51.05-server.txt](https://github.com/Momo-Studios/Cold-Sweat/files/8668886/crash-2022-05-11_05.51.05-server.txt)
[crash-2022-05-11_05.51.10-client.txt](https://github.com/Momo-Studios/Cold-Sweat/files/8668888/crash-2022-05-11_05.51.10-client.txt)

**Comment by MikulDev** [comment] 2022-05-16 17:09
This crash is actually a bit misleading. I've heard a lot of reports about the icebox causing a crash, but it's actually being caused by the waterskin itself being in your inventory. That's why it crashes when you try to rejoin.
This has already been addressed internally, and it will be fixed in the next update.

**Closed as completed** 2022-06-06 03:40 UTC
