### ISSUE TITLE
Sewing table won't work

### ISSUE THREAD

**Issue by ImReallyCreative** [Momo-Studios/Cold-Sweat-Rework-Forge#425] opened 2024-12-18 02:47 UTC
I'm using version 2.3.9 of cold sweat from modrinth on MC version 1.20.1. I've tested this on a completely clean install so I know for certain its not a compatibility issue. No config changes. I tried every combination of chestplate and insulator that I could think of and none of them would actually produce anything in the output slot. The materials did go correctly into the input slots. The log from that session: [https://mclo.gs/xlXNw4v](https://mclo.gs/xlXNw4v)

**Comment by SmArtKar** [comment] 2024-12-18 11:31
Duplicate of https://github.com/Momo-Softworks/Cold-Sweat/issues/414

**Comment by MikulDev** [comment] 2024-12-18 13:09
This is a known issue in 2.3.9. Please use 2.3.10 or 2.3.8

**Closed as completed by MikulDev** 2024-12-18 13:09 UTC
