### ISSUE TITLE
Incompatibility with VS ships

### ISSUE THREAD

**Issue by Belselk** [Momo-Studios/Cold-Sweat-Rework-Forge#187] opened 2023-11-01 09:21 UTC
With the Valkyries Skies + Eureka! mod, it is possible to build ships that actually move using blocks. However, the blocks on the ship cannot provide temperature change.
I am building a mobile base in VS and it is a shame that many of the facilities, including the boiler, no longer make sense.
I hope they can work well together.

VS: https://www.curseforge.com/minecraft/mc-mods/valkyrien-skies
Eureka!: https://www.curseforge.com/minecraft/mc-mods/eureka-ships

use version:
cold-swet 2.2 (1.19.2)
VS 1192-2.2.0-beta-3
Eureka! 1192-1.2.0-beta-1

**Comment by MikulDev** [comment] 2023-11-01 13:25
Duplicate of #162. Please see that issue for more info

**Closed as completed by MikulDev** 2023-11-01 13:25 UTC
