### ISSUE TITLE
Crash 1.20.1 || coldsweat-2.3-b03c

### ISSUE THREAD

**Issue by Stiles52** [Momo-Studios/Cold-Sweat-Rework-Forge#286] opened 2024-05-11 12:33 UTC
[crash-2024-05-11_14.28.43-client.txt](https://github.com/Momo-Softworks/Cold-Sweat/files/15282821/crash-2024-05-11_14.28.43-client.txt)

**Comment by MikulDev** [comment] 2024-05-13 00:08
This issue is a duplicate of #283 and #279. This will be fixed in the next beta version

**Closed as completed by MikulDev** 2024-05-13 00:08 UTC
