### ISSUE TITLE
[1.19.2 2.2-b04j] Fail to load world with Serene Seasons

### ISSUE THREAD

**Issue by BookerCatch** [Momo-Studios/Cold-Sweat-Rework-Forge#144] opened 2023-07-21 17:58 UTC
### Brief Summary of the Issue
World _occasionally_ fails to load with Serene Seasons installed. Must close client. 

### Mods of significant relevancy:
Forge 43.2.21
Cold Sweat 2.2-b04j
Serene Seasons 1.19.2-8.1.0.24
**Serene Seasons Fix 1.19.2-1.0.8**

The log file attached below provides some insight on when the issue occurs at **line 1093**. I'm using Serene Seasons Fix alongside Hourglass. The former's curseforge page explains some of the tick and time-related fixes it applies. I've only ever received this issue when Cold Sweat is loaded with Serene Seasons, so I'm not sure the Fix mod is responsible, but I thought it'd worth mentioning.

**Crash Report Link**
[latest.log](https://github.com/Momo-Studios/Cold-Sweat/files/12131182/latest.log)

**Comment by BookerCatch** [comment] 2023-07-21 18:15
I disabled Serene Seasons Fix and the issue persists.

**Comment by MikulDev** [comment] 2023-07-23 04:52
This is indeed an issue with the base Serene Seasons mod. I've already found a fix for this issue, and it will be posted soon.
Duplicate of #142

**Closed as completed by MikulDev** 2023-07-23 04:52 UTC
Labels: crash
