### ISSUE TITLE
Random Server Crash (1.19.2/ColdSweat-2.2-b04h.jar )

### ISSUE THREAD

**Issue by SHXRKIEgg** [Momo-Studios/Cold-Sweat-Rework-Forge#135] opened 2023-07-05 18:45 UTC
Hi me again, so this Crash happened randomly on my server test but is not reproducible and only happened once. Just reporting here incase it is an issue.

[(Crash Report Link)](https://pastebin.com/1ygzZR08)

**Comment by MikulDev** [comment] 2023-07-05 18:51
This is actually a duplicate of a few issues I've seen before, but it's not immediately obvious. This actually stems from chameleons, which try to detect the biome of an unloaded chunk if they are at the edge of the loaded "render distance". This has already been solved and will be fixed in the next beta.
Duplicate of #132

**Closed as completed by MikulDev** 2023-07-05 18:51 UTC
Labels: critical bug
