### ISSUE TITLE
Not compatible with the latest version of the Serene Seasons mod.

### ISSUE THREAD

**Issue by 7yudinglaopin8** [Momo-Studios/Cold-Sweat-Rework-Forge#391] opened 2024-10-15 15:26 UTC
There's nothing to say, literally.

**Comment by MikulDev** [comment] 2024-10-15 16:54
Duplicate of #384 and #390. Please search the previous issues before posting.

Serene Seasons made a large backend change between the last version and this one. Every mod that has compat with Serene Seasons is affected. Cold Sweat will be updated to address these changes soon.

**Closed as completed by MikulDev** 2024-10-15 16:54 UTC

**Comment by 7yudinglaopin8** [comment] 2024-10-16 08:19
> Duplicate of #384 and #390. Please search the previous issues before posting.
> 
> Serene Seasons made a large backend change between the last version and this one. Every mod that has compat with Serene Seasons is affected. Cold Sweat will be updated to address these changes soon.

Hurry up,plz...

**Comment by MikulDev** [comment] 2024-10-16 12:32
You can downgrade Serene Seasons to continue playing it with Cold Sweat. I will release the update when I can
