### ISSUE TITLE
Touch water=crash

### ISSUE THREAD

**Issue by 7yudinglaopin8** [Momo-Studios/Cold-Sweat-Rework-Forge#354] opened 2024-08-25 14:21 UTC
water,me,crash......
I don't know why.
Unexpected error
[crash-2024-08-25_19.58.28-client.txt](https://github.com/user-attachments/files/16740618/crash-2024-08-25_19.58.28-client.txt)

**Comment by MikulDev** [comment] 2024-08-25 14:27
Duplicate of #353. This will be fixed soon

**Closed as completed by MikulDev** 2024-08-25 14:27 UTC
Labels: duplicate
