### ISSUE TITLE
The game crashes on 1.20.1

### ISSUE THREAD

**Issue by FilipKompaniets3** [Momo-Studios/Cold-Sweat-Rework-Forge#301] opened 2024-05-24 16:41 UTC
Crash report: https://bytebin.lucko.me/9NyidHhrW3

I was playing on my mod pack and after I broke the gravel block I had a crash and the "Not Enough Crashes" mod started blaming the "Cold Sweat" mod.

**Comment by MikulDev** [comment] 2024-05-24 18:57
Duplicate of #299, #290, #286, and #283. This will be fixed in the next beta version

**Closed as completed by MikulDev** 2024-05-24 18:57 UTC

**Comment by FilipKompaniets3** [comment] 2024-05-25 15:09
Ок
