### ISSUE TITLE
ColdSweat randomly sometimes cant load world (1.19.2/ColdSweat-2.2-b04j.jar)

### ISSUE THREAD

**Issue by SHXRKIEgg** [Momo-Studios/Cold-Sweat-Rework-Forge#143] opened 2023-07-19 12:50 UTC
**Describe the bug**
Sometimes randomly the world doesnt want to load, this happened on a fresh world on the server, happenens on sp too

**To Reproduce**
1. Create Server
2. Random Chunk issue
3. See error not always

**Additional context**
[latest (1).log](https://github.com/Momo-Studios/Cold-Sweat/files/12095027/latest.1.log)

**Comment by SHXRKIEgg** [comment] 2023-07-19 13:03
This seed 847479976687857
it quite happened a lot in testing

**Comment by MikulDev** [comment] 2023-07-20 04:38
The reason behind this issue is the same as #142. Some registries from Cold Sweat aren't finished loading by the time entities (specifically Chameleons) start loading in, which causes an error as Chameleons rely on these registries to determine the temperature around them. This specific problem is most likely caused by Chameleons in your spawn chunks.
For now, you can "fix" this issue by removing Serene Seasons and Weather2 if you have either of them installed. This will be fixed soon.

**Closed as completed by MikulDev** 2023-07-20 04:38 UTC
Labels: bug, crash
