### ISSUE TITLE
Crash during overheating

### ISSUE THREAD

**Issue by Willem07** [Momo-Studios/Cold-Sweat-Rework-Forge#175] opened 2023-10-10 16:04 UTC
[latest.log](https://github.com/Momo-Softworks/Cold-Sweat/files/12859288/latest.log)

ColdSweat-2.2.1
1.20.1-forge-47.2.1

**Comment by MikulDev** [comment] 2023-10-16 03:25
Thanks for the report. The issue is now fixed.

**Closed as completed by MikulDev** 2023-10-16 03:25 UTC
