### ISSUE TITLE
[1.19.2] (Client Crash) "Index -1 out of bounds for length 2" on Tooltip? with JEI

### ISSUE THREAD

**Issue by BigMartin58** [Momo-Studios/Cold-Sweat-Rework-Forge#293] opened 2024-05-15 03:31 UTC
Just had a crash when looking at a recipe in JEI of Immersive Engineering 'Slag' under I believe the 'Chemical Dissolution' page for Chemlib and their was a Barrier Block Icon, and when I hovered over it, I crashed. I have 'Not Enough Crashes' and it says that Cold Sweat and JEI are at fault. Further review looks like a tooltip tried to render an index that was out of bounds, but I'm not an expert with crash logs.

Crash Log: https://mclo.gs/deyDqAq

If you believe it was caused by another mod, let me know I will post it on their GitHub.

**Comment by MikulDev** [comment] 2024-05-16 01:21
Duplicate of #290. This will be fixed in the next version.

**Closed as completed by MikulDev** 2024-05-16 01:21 UTC
