### ISSUE TITLE
This mod is preventing the "Filter" item from Create from opening

### ISSUE THREAD

**Issue by Zanklev** [Momo-Studios/Cold-Sweat-Rework-Forge#276] opened 2024-05-02 08:04 UTC
https://github.com/Momo-Softworks/Cold-Sweat/assets/139833714/9b9f3301-f104-4a61-8f2c-1dcefeed2823

While this mod is installed, you cannot open the settings of the "Filter" item on Create.

On Forge 1.20.1
ColdSweat-2.3-b03a

I did a fresh install with only "Create" and "Cold Sweat"

**Comment by gabriel-eladi** [comment] 2024-05-02 18:39
i also experienced this issue.
i'm playing on 1.19.2, Forge version 43.3.13, Create version 0.5.1.f.
this happens on the latest beta of Cold Sweat (2.3-b03a) but not on the latest release (2.2.5.1).

**Comment by MikulDev** [comment] 2024-05-04 00:57
Duplicate of #270. This will be fixed in the next version

**Closed as completed by MikulDev** 2024-05-04 00:57 UTC
