### ISSUE TITLE
[1.20.1] Item stacking issue

### ISSUE THREAD

**Issue by xhatz** [Momo-Studios/Cold-Sweat-Rework-Forge#235] opened 2024-03-15 20:24 UTC
Hello! I have found a bug with the mod installed alone (latest version). When the inventory gets updated, so does all the items in it, this causes a weird bug where new picked up items come with no tag and does not stack with others. I suck at explaining things in english so here is how to easily reproduce:

- Dig some dirt, pick it up,
- Move the dirt you picked up to another slot in your inventory,
- Dig another dirt, it won't stack with the first one.

**Comment by sillypickly45** [comment] 2024-03-16 23:47
Same issue, seems unaffected by other mods

**Comment by MikulDev** [comment] 2024-03-18 04:35
Duplicate of #232. This will be fixed in the next update.

**Closed as completed by MikulDev** 2024-03-18 04:35 UTC

**Comment by xhatz** [comment] 2024-03-20 19:35
Sadly the latest patch did not fix the issue :(

**Comment by xhatz** [comment] 2024-03-20 19:35
Sadly the latest patch did not fix the issue it seems, @MikulDev :(
Items can now be stacked, but the behavior when updating the inventory, and mining another block still causes the non-stacking issue.
