### ISSUE TITLE
Insulation doesn't work at all

### ISSUE THREAD

**Issue by RichPrune** [Momo-Studios/Cold-Sweat-Rework-Forge#141] opened 2023-07-19 04:06 UTC
**Describe the bug**
Any time i apply leather to a sewing kit to armor, or wear goat or hoglin armor, none of it affects my temperature at all. I still die extremely quickly in the nether. 
**To Reproduce**
1. Go to the game
2. Get leather/insulating armor
3. Equip insulated armor
4. Doesn't change temperature at all anywhere

**Expected behavior**
You said in your description it should be 3x slower to change temperature, but it's not changed at all

**Additional context**
I tested in cold biomes, deserts, savannas, and the nether; soul lantern works but i shouldn't have to get a crop from the nether to survive in the nether while holding an item; blocks i tested work

**Comment by MikulDev** [comment] 2023-07-20 04:30
It definitely works in my testing. You didn't say what version you're using, but in the latest version on 1.19.2 it does indeed slow down the change. Maybe not quite by 3x anymore (I may need to rebalance that), but it's at least halved.
Check your configs if you aren't getting this result. Try deleting them and allowing the mod to regenerate them.

**Comment by RichPrune** [comment] 2023-07-21 05:54
its forge 1.19.2 as well, latest update. i wish i had the ability to control how much insulating gave you in terms of time that would solve everything really; also it's stupid that the only viable way to survive in the nether is the soul lantern that lasts for 20 min; insulation to me is just a much better mechanic for temperature

**Comment by MikulDev** [comment] 2023-07-21 13:34
You can increase the amount of insulation that items provide in the configs. You can also change the rate at which the player's temperature changes. And on top of that you can use fire resistance to become completely immune to heat for the duration of the potion

**Comment by RichPrune** [comment] 2023-07-23 21:19
well that option doesn't work at all either; because again insulation doesn't do anything. No matter what value I set hog armor, goat armor, leather insulation, etc. to it doesn't slow or speed up burning or freezing at all. As for potions you really shouldn't need to use potions all the time just to exist in major areas of progression imo; especially when those potions come from the place you're trynna survive. It's like saying you need work experience to work your first job

**Comment by RichPrune** [comment] 2023-07-23 21:20
potions should just be one way of doing it is what im trynna say

**Comment by MikulDev** [comment] 2023-07-24 00:26
What I'm trying to say is that there are many, many ways to survive if you're resourceful, and you can also tweak everything in the configs. I'm using 2.2-b04j and can't get insulation to _not_ work, so I'm not sure why this issue is occurring. I'll be releasing a new version soon, so try on that and see if the problem is solved.

**Comment by RichPrune** [comment] 2023-07-26 17:51
will do

**Comment by MikulDev** [comment] 2023-08-04 15:16
Is the problem still present? I will be closing this issue if I don't get a response soon.

**Closed as completed** 2023-08-07 23:12 UTC
Labels: bug
