### ISSUE TITLE
Incompatibility with Fancy Menu

### ISSUE THREAD

**Issue by tr1kright** [Momo-Studios/Cold-Sweat-Rework-Forge#289] opened 2024-05-12 20:11 UTC
**Describe the issue**
Hovered over an item and the game crashed, crash-reports says the problem is in these two mods (I'm not a native English speaker, I use a translator)

[**crash-report**](https://gist.github.com/tr1kright/7f72e4f56cde1c73c330ce0ecccc399c)
[**latest.log**](https://gist.github.com/tr1kright/d08782dd1ac9071345a0cb7b024ae288)

https://github.com/Keksuccino/FancyMenu/issues/785#issue-2246914444

UPD: these are old logs, the current ones should have FancyMenu 3.2.2 and ColdSweat 2.3-b03c, but the error is the same

**Comment by MikulDev** [comment] 2024-05-13 00:08
This issue is a duplicate of #286, #283, and #279. This will be fixed in the next beta version

**Closed as completed by MikulDev** 2024-05-13 00:08 UTC
