### ISSUE TITLE
Goat Fur/Fur

### ISSUE THREAD

**Issue by Shadow-player** [Momo-Studios/Cold-Sweat-Rework-Forge#254] opened 2024-03-31 17:45 UTC
Playing the 21.5 version of STEAMPUNK
Minecraft 1.19.2
Windows 11
Forge

The sewing table from Cold Sweat doesn't accept "FUR" which is sheared from goats.
Chameleon Molt and Hoglin skin work fine.

**Comment by MikulDev** [comment] 2024-03-31 18:36
Please take this up with the modpack authors. Their config settings for fur stuff are broken

**Comment by Shadow-player** [comment] 2024-04-01 01:32
They told me to tell you....
Thanks!

**Comment by MikulDev** [comment] 2024-04-01 01:42
Oh, I see. Didn't know you went to them first. I've looked into the configs myself. They're missing the entries for fur.

**Comment by inyobase** [comment] 2024-04-05 18:00
just checked the item settings in my server for the HF22 version  and the following line is there:
"Insulation Ingredients" = [["minecraft:rabbit_hide", 0.0, 1.5], ["minecraft:leather_chestplate", 6.0, 6.0], ["minecraft:leather_boots", 4.0, 4.0], ["minecraft:leather", 1.0, 1.0], ["cold_sweat:hoglin_trousers", 0.0, 10.0], ["cold_sweat:hoglin_hide", 0.0, 2.0], ["cold_sweat:hoglin_headpiece", 0.0, 8.0], ["cold_sweat:hoglin_tunic", 0.0, 12.0], ["environmental:yak_hair", 1.5, -1.0], ["minecraft:leather_leggings", 5.0, 5.0], ["minecraft:leather_helmet", 4.0, 4.0], ["cold_sweat:hoglin_hooves", 0.0, 8.0], ["cold_sweat:fur_cap", 8.0, 4.0], ["minecraft:fur_pants", 10.0, 5.0], ["minecraft:fur_boots", 8.0, 4.0], ["minecraft:fure_parka", 12.0, 6.0], ["minecraft:leather_boots", 4.0, 2.0], ["minecraft:fur", 3.0, 0.0]]
it does seem to have the cold sweat fur outfit, and the minecraft:fur  as ingredients, but I too was unable to add it to gear in the sewing table.

Edit: my 21.5 world also has the identical lines in that config, its paths were the "config\coldsweat\iten_settings.toml

**Comment by MikulDev** [comment] 2024-04-05 18:25
The item IDs for the fur items have "minecraft:" at the beginning, which is wrong. It should be "cold-sweat:" i.e. "cold-sweat:fur".
The fur parka is also misspelled

**Comment by inyobase** [comment] 2024-04-05 19:26
> The item IDs for the fur items have "minecraft:" at the beginning, which is wrong. It should be "cold-sweat:" i.e. "cold-sweat:fur". The fur parka is also misspelled

good to know, thank you for the reply, ill make the changes to my own configs, hopefuly the original author can re contact the modpack author.

**Comment by MikulDev** [comment] 2024-04-05 23:02
Alright, I'll be closing this issue since it's confirmed to be a problem on their side.

**Closed as completed by MikulDev** 2024-04-05 23:02 UTC
