### ISSUE TITLE
Incompatibility With ReBlured

### ISSUE THREAD

**Issue by SaltSouls** [Momo-Studios/Cold-Sweat-Rework-Forge#188] opened 2023-11-07 10:55 UTC
## Description:
The shader for heatstroke remains permanently after entering a menu during or shortly after the shader kicks in. You can temporarily fix it by overheating your character again, but each time you open a menu afterwards, the bug will come back.

### Versions:
- Minecraft: 1.20.1
- Forge: 47.2.4
- Cold Sweat: 2.2.2
- ReBlured: 1.3.0

**Comment by MikulDev** [comment] 2023-11-11 18:27
I think this might actually be a problem with ReBlured. Looking at their source code, it seems like they store the current screen effect (shader) when you open a menu, apply their own shader when the screen is open, then put the old shader back when the menu is closed. 
The issue is that they don't remove the shader from storage when Cold Sweat clears the blur effect (when your temperature goes back to below 50), so when the shader is removed ReBlured just puts it back again at full intensity.

**Comment by SaltSouls** [comment] 2023-11-11 19:00
Thanks, I'll report this to them!

**Comment by MikulDev** [comment] 2023-12-02 14:25
I will be closing this issue for now. I'll reopen it if there's any news

**Closed as completed by MikulDev** 2023-12-02 14:25 UTC
