### ISSUE TITLE
2.3-b03b Temps are broken

### ISSUE THREAD

**Issue by DeshiDesu** [Momo-Studios/Cold-Sweat-Rework-Forge#277] opened 2024-05-04 03:06 UTC
1.20.1
Forge 47.2.30
ColdSweat-2.3-b03b.jar

Temps can easily reach -5000 when in water

2.3-b03b:
![2024-05-03_22 59 12](https://github.com/Momo-Softworks/Cold-Sweat/assets/120287925/d5635d8d-3d4e-40e3-8c92-8b6a03846dd6)

2.3-b03a:
![image](https://github.com/Momo-Softworks/Cold-Sweat/assets/120287925/8e795454-c0e3-4ef4-8e29-e9035eb43447)

**Comment by MikulDev** [comment] 2024-05-04 07:08
Yeah, I would definitely consider this "broken". Thanks for bringing this to my attention.

**Comment by Zanklev** [comment] 2024-05-04 10:02
Ya I can second this, just discovered it myself

**Comment by mortuusars** [comment] 2024-05-04 18:29
Rain has the same effect.
![2024-05-04_21 28 40](https://github.com/Momo-Softworks/Cold-Sweat/assets/65141267/a1a2b8df-3cc6-46dd-99e5-adf90e068397)

**Comment by gluzzie** [comment] 2024-05-04 19:13
Also in this version you cannot open the settings for cold sweat

**Comment by MikulDev** [comment] 2024-05-05 02:54
I've found the source of the issue. As you probably could have guessed, the wet effect caused by water and rain was stacking infinitely instead of just being applied once. This will be fixed in the next version

**Closed as completed by MikulDev** 2024-05-05 02:54 UTC
