### ISSUE TITLE
Server crashing after falling behind on ticks (MC 1.18.2/ColdSweat-2.2-b04h)

### ISSUE THREAD

**Issue by Ishumire** [Momo-Studios/Cold-Sweat-Rework-Forge#133] opened 2023-07-04 13:41 UTC
There's over 180 mods in my server, i've been trying to fix this issue for a while, but the crash reports were being very unhelpful.
Finally, i found a mention of Cold Sweat, and removing it stopped the crashing.

[crash-2023-07-03_23.43.21-server.txt](https://github.com/Momo-Studios/Cold-Sweat/files/11949888/crash-2023-07-03_23.43.21-server.txt)

**Comment by MikulDev** [comment] 2023-07-05 19:05
This issue will be fixed in 2.2-b04i
Duplicate of #132

**Closed as completed by MikulDev** 2023-07-05 19:05 UTC
Labels: critical bug
