### ISSUE TITLE
[1.16.5] AMD GPU driver related JRE crash (Combat Roll incompatibility)

### ISSUE THREAD

**Issue by Mic1e** [Momo-Studios/Cold-Sweat-Rework-Forge#193] opened 2023-11-16 21:51 UTC
Hi,
Me and a friend are playing on a modpack we put together and we have encountered what seems to be a weird and specific bug that only seems to happen with Cold Sweat. We haven't yet tested all possibilities but here is what we have right now.

- Forge - v1.16.5-36.2.39
- Cold Sweat - v2.2
- Java 8 and 11
- AMD RX 6600 XT

The following is the fatal error message that gets shown in the console:
```
A fatal error has been detected by the Java Runtime Environment:
#
EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007fff2d5be605, pid=10152, tid=5172
#
JRE version: OpenJDK Runtime Environment Temurin-11.0.19+7 (11.0.19+7) (build 11.0.19+7)
Java VM: OpenJDK 64-Bit Server VM Temurin-11.0.19+7 (11.0.19+7, mixed mode, tiered, compressed oops, g1 gc, windows-amd64)
Problematic frame:
C  [atio6axx.dll+0x214e605]
#
No core dump will be written. Minidumps are not enabled by default on client versions of Windows
#
An error report file with more information is saved as:
<redacted>
```
From what I have seen `atio6axx.dll` means it's something to do with the AMD GPU driver.

The crash only seems to happen under these conditions and when the body temp. reaches roughly around or above 50:
- Survival mode.
- In the Nether dimension.
- No Cold Sweat grace period effect.

We have not tested yet with just Cold Sweat and other mods disabled but the crash no longer happens when Cold Sweat is disabled.

I will post any updates as we do more tests. Any help is greatly appreciated.

[debug.log](https://github.com/Momo-Softworks/Cold-Sweat/files/13384471/debug.log)

**Comment by Mic1e** [comment] 2023-11-17 04:48
AMD GPU driver version - 23.11.1
Combat Roll - 1.0.8.2+1.16
Player Animator - 0.4.0+1.16.5
ForgedFabric API - 0.0.7+1.16
Cloth Config - 4.17.101

Did something more testing with my friend and we have narrowed it down to Cold Sweat and Combat Roll being incompatible. Leaving Combat Roll's dependencies enabled without Combat Roll itself enabled makes no difference.
The crash happens exactly when the body temp. reaches 49/50, that's when Cold Sweat starts to apply visual effects to the screen.

Edit: Running either Cold Sweat or Combat Roll alone works fine.

**Comment by Mic1e** [comment] 2023-11-17 04:59
Another update and probably the last one. The issue no longer exists when disabling Cold Sweat's distortion effects.

**Comment by MikulDev** [comment] 2023-11-18 23:01
I'm not sure what combat roll does with rendering, but it should be fine to just disable distortion effects. It's likely the blur shader causing the crash, since shaders in Minecraft are pretty temperamental.

**Comment by Mic1e** [comment] 2023-11-19 22:10
Yeah, I'm not sure either, the only rendering that Combat Roll does that I'm aware of is one thing for the HUD, maybe there is some issue with how that's done on their end and the distortion effects from Cold Sweat. It only happens on my friend's system though so we just disabled the option for now. I'd say we would welcome a fix if possible but won't be expecting one so you can close this issue if you want. Thanks.

**Comment by MikulDev** [comment] 2023-11-20 02:14
Unfortunately, these kinds of graphical issues are way over my head. I've also heard of similar issues with AMD cards, but they usually trigger with just Cold Sweat installed. I personally haven't experienced it and I have an AMD GPU, so it's not something I can reproduce. 
Anyway, I'll be closing this issue because I don't think I'll be able to fix it.

**Closed as completed by MikulDev** 2023-11-20 02:14 UTC
